### ISSUE TITLE
Bug in encoding SL/SR/SLC/SRC

### ISSUE THREAD

**Issue by cpldcpu** [Rakete1111/sdcc-pdk#1]
Hi, 

first, thanks a lot for your work on SDASPDK. I have been testing it during the last days with actual hardware (PFS154). I found one bug in instruction enconding

https://github.com/Rakete1111/sdcc-pdk/blob/dfc687c3c36d01f1a7505231c7c602725496275f/sdas/aspdk/pdkmch.c#L154

I fixed it like this. Sorry for not providing an actual pull request.

```
        case S_SLC:
        case S_SRC:
        case S_SL:
        case S_SR:
                if (mp->m_type == S_SRC || mp->m_type == S_SLC)
                        combine = 2;
                if (mp->m_type == S_SL || mp->m_type == S_SLC)
                        combine += 1;

                t = addr(&e);

                if (t == S_A) {
                        op = (0x006A + combine);
                } else
                if (t == S_M) {
                        op = (0x1500 + (combine<<7));
                        op |= e.e_addr & 0x7F;
                } else
                        aerr();

                outaw(op);
                break;
```

**Comment by Rakete1111** [comment]
Thank you! I'll fix it right away. (This repo is not really up-to-date anymore; hope you're using the official pdk branch of sdcc).

Rebased anyway.

**Comment by cpldcpu** [comment]
Thanks! No, I have been using Philipps branch via SVN.

**Comment by Rakete1111** [comment]
Cool :) It might take a while though for the patch to land there.
