### ISSUE TITLE
PDK13

### ISSUE THREAD

**Issue by cpldcpu** [Rakete1111/sdcc-pdk#2]
Hi,

how about adding PDK13 support? Would it be necessary to come up with a completely separate breanch of SDAS or is there a clean option of integrating it into the existing SDASPDK? I have no idea about the overall structure of SDCC, but if this is addressed I would offer to adapt the code generator.

Regards,
Tim

**Comment by Rakete1111** [comment]
Yes, pdk13 (and the others) is planned. I imagine that it is not needed to create new assemblers just for them.
